### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by UXplayer** [wufeng-tech/AppHub#1]
1. 最好说明一下安装方式，不然小白直接丧失使用的动力了
2. 最好提供个docker 
3. 最好说明下配置文件在哪、还有token是怎么配置

**Comment by w4mxl** [comment]
谢谢你给我们提的建议

1. 在 Readme 的末尾添加了安装依赖和部署说明
2. 暂时还提供不了，后面会考虑做一下
3. token 目前是写死的
